# Generated by Django 4.2.6 on 2023-11-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receita', '0003_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
